### ISSUE TITLE
The movie is marked as available even though only the 4K version is.

### ISSUE THREAD

**Issue by JolanLar** [Fallenbagel/jellyseerr#367]
### Description

When a movie is downloaded only in 4K, it is marked as "available" and "4K available", so we cannot request it in HD.
I haven't tested it for TV shows, but it might also be the case.

### Version

1.4.1

### Steps to Reproduce

1. 4K radarr instance needed
2. Go on a movie
3. Ask for the movie in 4K
4. Waiting for the movie to download
5. The movie is marked available

### Screenshots

![image](https://user-images.githubusercontent.com/57663724/232108954-0aa8b0a5-2ea7-4bd3-9ac0-4ec27b2899d6.png)
![image](https://user-images.githubusercontent.com/57663724/232109249-925d1d91-ae8f-4022-9016-ab89ebeffe16.png)

The movie in jellyfin :
![image](https://user-images.githubusercontent.com/57663724/232109438-35d76b6c-6826-40aa-b257-120ec360f3b1.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Chrome

### Additional Context

My Jellyseerr instance is hosted on Docker using the 'latest' tag.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This is already fixed and will be available in the next branch. If you want to try it out you can also try it using the development tag. You'll have to manually clear data of the media affected tho

**Comment by Rover1176** [comment]
I am also facing the same issue. I am using 1.5.0 version currently

**Comment by Fallenbagel** [comment]
> I am also facing the same issue. I am using 1.5.0 version currently

You might wanna clear data and rescan. That will fix it with the new version

**Comment by Rover1176** [comment]
I have started using jellyseerr from the 1.5.0 version. Just set it up yesterday. I did the rescan now but that didn't fix the issue. (I am using the merge versions plugin in jellyfin btw)

**Comment by Rover1176** [comment]
I tested the same on shows, and it seems to work fine with the 4k-only shows. Only The 4k-only movies are experiencing this issue.

**Comment by Rover1176** [comment]
4k and 1080p movies are in separate folders in the filesystem. Still, in Jellyfin, all these folders are added to the same library, and I use the merge versions plugin in Jellyfin to combine different versions if they exist.

It is the same as above with shows too. But shows have no issues.

**Comment by Fallenbagel** [comment]
> 4k and 1080p movies are in separate folders in the filesystem. Still, in Jellyfin, all these folders are added to the same library, and I use the merge versions plugin in Jellyfin to combine different versions if they exist.
> 
> It is the same as above with shows too. But shows have no issues.

Could you try putting two test ones in two seperate libraries and see if they detect? (As so far everyone who reported before show fix and after show fix mentioned that movies were working fine. It was the shows that were borked and after the fix they mentioned shows were working as well)

**Comment by Rover1176** [comment]
I don't understand what you mean by putting 2 files in separate libraries.😅

I think I wasn't clear in explaining my issue😅.

The issue is when I have only one version of the movie (4k), jellyseerr is falsely detecting that both versions exist.(which isn't true).

This is what is happening currently in my library.

Scenario 1:
4k version exists in jellyfin
1080p version exists in jellyfin

Jellyseerr shows both as available.

Scenario 2:
4k version doesn't exist in jellyfin
1080p version exists in jellyfin

Jellyseerr shows that 1080p is available along with an option to request for 4k.

Scenario 3(the issue):
4k version exists in jellyfin
1080p version doesn't exist in jellyfin

Jellyseerr shows that both versions are available(even though 1080p actually isn't available).

What else should I test to diagnose the issue? Are there any logs I can provide?

Thanks for responding so quickly and trying to solve my issue.

**Comment by Fallenbagel** [comment]
@Rover1176 could you reach out on discord server so its easier to troubleshoot? I'll update here once done

**Comment by Fallenbagel** [comment]
This was fixed in bc9017f54d84ec24c4d74d38e1b4e24219425d41 and 3bf04f2abd96bf95a1363dd16e4de46cf621ab5d
